server:
  port: 8088

spring:
  datasource:
    username: root
    password: no.tt@cpm956
    url: jdbc:mysql://123.57.186.69:3306/MedicineMall?useSSL=false&serverTimezone=UTC&allowMultiQueries=true
    driver-class-name: com.mysql.cj.jdbc.Driver

#开启mybatis-plus日志
#mybatis-plus:
##  configuration:
##  #    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
##  #开启自动驼峰命名规则（camel case）映射
##    mapUnderscoreToCamelCase: true

mybatis:
  mapper-locations: classpath*:pers/ervinse/mapper/*.xml
  type-aliases-package: pers.ervinse.domain
  #设置 mapper接口中 自定义方法的sql语句 所对应的XML文件位置
  #(Maven 多模块项目的扫描路径需以classpath*:开头(即加载多个 jar 包下的 XML 文件))


page helper:
  helper-dialect: mysql

